(in-package #:llm-log-expert)

(defparameter +task-schema-version+ 1)
(defparameter +usage-schema-version+ 1)
(defparameter +pricing-schema-version+ 1)
(defparameter +cost-schema-version+ 1)

(defun %task-key (task-id) (format nil "task:~A" task-id))
(defun %usage-key (usage-id) (format nil "usage:~A" usage-id))
(defun %pricing-key (snapshot-id) (format nil "pricing:~A" snapshot-id))
(defun %cost-key (usage-id) (format nil "cost:~A" usage-id))

(defun %required-json-string (object field)
  (let ((value (jsown:val-safe object field)))
    (unless (%non-empty-string-p value)
      (error "~A is required" field))
    value))

(defun %optional-number (object field)
  (let ((value (jsown:val-safe object field)))
    (when value
      (unless (numberp value) (error "~A must be numeric" field)))
    value))

(defun %put-immutable (host key projection conflict-label)
  (let ((database (expert-host-database host)))
    (with-write-transaction (database)
      (let ((existing (fetch* database key))
            (revision (or (fetch* database +kb-revision-key+) 1)))
        (cond
          ((null existing)
           (let ((next (1+ revision)))
             (put* database projection :id key)
             (put* database next :id +kb-revision-key+)
             (values :created next)))
          ((equal existing projection) (values :existing revision))
          (t (error "~A_conflict: ~A" conflict-label key)))))))

(defun %task-projection (task &optional parent-id)
  (let ((task-id (%required-json-string task "task_id")))
    (list :schema-version +task-schema-version+
          :task-id task-id
          :parent-task-id (or (jsown:val-safe task "parent_task_id") parent-id)
          :session-id (jsown:val-safe task "session_id")
          :originating-user-message-id (jsown:val-safe task "originating_user_message_id")
          :rule-id (%required-json-string task "rule_id")
          :rule-version (jsown:val-safe task "rule_version")
          :evidence-ids (copy-list (or (jsown:val-safe task "evidence_ids") '())))))

(defun %usage-projection (usage)
  (list :schema-version +usage-schema-version+
        :usage-id (%required-json-string usage "usage_id")
        :request-id (%required-json-string usage "request_id")
        :task-id (%required-json-string usage "task_id")
        :provider (%required-json-string usage "provider")
        :model (%required-json-string usage "model")
        :input-tokens (%optional-number usage "input_tokens")
        :output-tokens (%optional-number usage "output_tokens")
        :cached-input-tokens (%optional-number usage "cached_input_tokens")
        :cached-output-tokens (%optional-number usage "cached_output_tokens")
        :reasoning-tokens (%optional-number usage "reasoning_tokens")))

(defun %pricing-projection (snapshot)
  (list :schema-version +pricing-schema-version+
        :snapshot-id (%required-json-string snapshot "snapshot_id")
        :provider (%required-json-string snapshot "provider")
        :model (%required-json-string snapshot "model")
        :currency (%required-json-string snapshot "currency")
        :effective-at (%required-json-string snapshot "effective_at")
        :source (%required-json-string snapshot "source")
        :source-version (%required-json-string snapshot "source_version")
        :input-per-token (%optional-number snapshot "input_per_token")
        :output-per-token (%optional-number snapshot "output_per_token")))

(defun %find-pricing-snapshot (usage snapshots)
  (find-if (lambda (snapshot)
             (and (equal (jsown:val-safe snapshot "provider")
                         (jsown:val-safe usage "provider"))
                  (equal (jsown:val-safe snapshot "model")
                         (jsown:val-safe usage "model"))))
           snapshots))

(defun %prolog-cost (host usage snapshot)
  (let* ((known (not (null snapshot)))
         (data (%json-object
                (cons "pricing_state" (if known "known" "unknown"))
                (cons "input_tokens" (or (jsown:val-safe usage "input_tokens") 0))
                (cons "output_tokens" (or (jsown:val-safe usage "output_tokens") 0))
                (cons "input_per_token" (if known (or (jsown:val-safe snapshot "input_per_token") 0) 0))
                (cons "output_per_token" (if known (or (jsown:val-safe snapshot "output_per_token") 0) 0))))
         (reply (prolog-worker-request host "task_cost" data)))
    (unless (equal (jsown:val-safe reply "status") "ok")
      (error "reasoner_error: ~A" (jsown:to-json reply)))
    (let* ((result (jsown:val-safe reply "result"))
           (state (jsown:val-safe result "state"))
           (amount (jsown:val-safe result "amount"))
           (rule-version (jsown:val-safe reply "rule_version")))
      (unless (member state '("known" "unknown") :test #'equal)
        (%reject-invalid-reasoner-result host "task_cost returned invalid state"))
      (when (and (equal state "known") (not (numberp amount)))
        (%reject-invalid-reasoner-result host "task_cost known state requires numeric amount"))
      (values state amount rule-version))))

(defun %cost-projection (usage snapshot state amount rule-version)
  (let ((usage-id (%required-json-string usage "usage_id")))
    (list :schema-version +cost-schema-version+
          :cost-assertion-id (format nil "cost/~A" usage-id)
          :task-id (%required-json-string usage "task_id")
          :request-id (%required-json-string usage "request_id")
          :usage-observation-id usage-id
          :pricing-snapshot-id (and snapshot (%required-json-string snapshot "snapshot_id"))
          :state state
          :amount amount
          :currency (and snapshot (jsown:val-safe snapshot "currency"))
          :rule-id "task.cost"
          :rule-version rule-version
          :expert-version "task-accounting/1"
          :evidence-ids (list usage-id))))

(defun account-task-usage (host payload)
  "Persist one bounded task fragment and derive per-request cost through declared Prolog rules."
  (let* ((task (jsown:val-safe payload "task"))
         (children (or (jsown:val-safe payload "children") '()))
         (usages (or (jsown:val-safe payload "usage_observations") '()))
         (snapshots (or (jsown:val-safe payload "pricing_snapshots") '())))
    (unless (and (consp task) (eq (first task) :obj)) (error "task must be an object"))
    (when (> (length children) 64) (error "too many children"))
    (when (> (length usages) 256) (error "too many usage observations"))
    (when (> (length snapshots) 128) (error "too many pricing snapshots"))
    (let* ((task-id (%required-json-string task "task_id"))
           (task-projection (%task-projection task)))
      (%put-immutable host (%task-key task-id) task-projection "task")
      (dolist (child children)
        (let* ((projection (%task-projection child task-id))
               (child-id (getf projection :task-id)))
          (%put-immutable host (%task-key child-id) projection "task")))
      (dolist (snapshot snapshots)
        (let* ((projection (%pricing-projection snapshot))
               (snapshot-id (getf projection :snapshot-id)))
          (%put-immutable host (%pricing-key snapshot-id) projection "pricing")))
      (let ((seen-requests '())
            (known-total 0)
            (known-currency nil)
            (known-snapshot-id nil)
            (unknown-p nil))
        (dolist (usage usages)
          (let ((request-id (%required-json-string usage "request_id")))
            (unless (member request-id seen-requests :test #'equal)
              (push request-id seen-requests)
              (let* ((usage-projection (%usage-projection usage))
                     (usage-id (getf usage-projection :usage-id))
                     (snapshot (%find-pricing-snapshot usage snapshots)))
                (%put-immutable host (%usage-key usage-id) usage-projection "usage")
                (multiple-value-bind (state amount rule-version)
                    (%prolog-cost host usage snapshot)
                  (let ((cost (%cost-projection usage snapshot state amount rule-version)))
                    (%put-immutable host (%cost-key usage-id) cost "cost"))
                  (if (equal state "known")
                      (progn
                        (incf known-total amount)
                        (unless known-currency (setf known-currency (jsown:val-safe snapshot "currency")))
                        (unless known-snapshot-id (setf known-snapshot-id (jsown:val-safe snapshot "snapshot_id"))))
                      (setf unknown-p t)))))))
        (%json-object
         (cons "task_id" task-id)
         (cons "pricing_snapshot_id" known-snapshot-id)
         (cons "known_cost_currency" known-currency)
         (cons "known_cost_amount" known-total)
         (cons "unknown_cost_state" (if unknown-p "unknown" "known"))
         (cons "request_count" (length seen-requests))
         (cons "kb_revision" (current-kb-revision host)))))))
