routing_correlation_source('routing.jsonl').
recovery_correlation_source('recoveries.jsonl').

routing_metadata_header(openrouter, 'X-OpenRouter-Metadata', enabled).
routing_metadata_scope(openrouter_only).

routing_observation_invariant(allowlisted_metadata_only).
routing_observation_invariant(raw_error_message_not_persisted).
routing_observation_invariant(endpoint_blob_not_persisted).
routing_observation_invariant(quantization_not_in_transport_routing_evidence).
routing_observation_invariant(stable_routing_id_per_event).
routing_observation_invariant(error_links_to_persisted_routing_observation).

routing_observation_field(selected_provider).
routing_attempt_field(provider).
routing_attempt_field(status).
routing_attempt_field(error_code).

retry_correlation_basis(byte_identical_request_sha256_within_window).
retry_correlation_window_seconds(10).
retry_correlation_confidence(heuristic).
retry_correlation_invariant(client_disconnect_never_candidate).
retry_correlation_invariant(hash_mismatch_never_matches).
retry_correlation_invariant(expired_window_never_matches).
retry_correlation_invariant(nearest_unconsumed_failure_matches_first).
retry_correlation_invariant(recovery_consumes_one_failure_once).
retry_correlation_invariant(pending_failure_survives_restart).
retry_correlation_invariant(no_automatic_retry_execution).

recovery_evidence_field(failed_event_id).
recovery_evidence_field(retry_event_id).
recovery_evidence_field(request_sha256).
recovery_evidence_field(failed_error_class).
recovery_evidence_field(retry_delay_ms).
recovery_evidence_field(failed_selected_provider).
recovery_evidence_field(retry_selected_provider).
recovery_evidence_field(provider_changed).
recovery_evidence_field(correlation_basis).
recovery_evidence_field(confidence).
